[package]
name = "dyfi-client"
version = "0.2.1"
authors = ["Ronja Koistinen <ronja.koistinen@kapsi.fi>"]
edition = "2018"

[dependencies]
reqwest = { version = "^0.10", features = ["blocking"] }
dotenv = "^0.15"
log = "^0.4"
env_logger = "^0.7"

# Pi 2/3/4
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-none-linux-gnueabihf-gcc"
